// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"bookshop/backend/internal/domain/publishers/entities"
	"context"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPublishers creates a new instance of MockPublishers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublishers(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublishers {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockPublishers{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockPublishers is an autogenerated mock type for the Repository type
type MockPublishers struct {
	mock.Mock
}

type MockPublishers_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublishers) EXPECT() *MockPublishers_Expecter {
	return &MockPublishers_Expecter{mock: &_m.Mock}
}

// CreatePublisher provides a mock function for the type MockPublishers
func (_mock *MockPublishers) CreatePublisher(context1 context.Context, publisher entities.Publisher) (entities.Publisher, error) {
	ret := _mock.Called(context1, publisher)

	if len(ret) == 0 {
		panic("no return value specified for CreatePublisher")
	}

	var r0 entities.Publisher
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Publisher) (entities.Publisher, error)); ok {
		return returnFunc(context1, publisher)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Publisher) entities.Publisher); ok {
		r0 = returnFunc(context1, publisher)
	} else {
		r0 = ret.Get(0).(entities.Publisher)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Publisher) error); ok {
		r1 = returnFunc(context1, publisher)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPublishers_CreatePublisher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePublisher'
type MockPublishers_CreatePublisher_Call struct {
	*mock.Call
}

// CreatePublisher is a helper method to define mock.On call
//   - context1 context.Context
//   - publisher entities.Publisher
func (_e *MockPublishers_Expecter) CreatePublisher(context1 any, publisher any) *MockPublishers_CreatePublisher_Call {
	return &MockPublishers_CreatePublisher_Call{Call: _e.mock.On("CreatePublisher", context1, publisher)}
}

func (_c *MockPublishers_CreatePublisher_Call) Run(run func(context1 context.Context, publisher entities.Publisher)) *MockPublishers_CreatePublisher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Publisher
		if args[1] != nil {
			arg1 = args[1].(entities.Publisher)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPublishers_CreatePublisher_Call) Return(publisher1 entities.Publisher, err error) *MockPublishers_CreatePublisher_Call {
	_c.Call.Return(publisher1, err)
	return _c
}

func (_c *MockPublishers_CreatePublisher_Call) RunAndReturn(run func(context1 context.Context, publisher entities.Publisher) (entities.Publisher, error)) *MockPublishers_CreatePublisher_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePublisher provides a mock function for the type MockPublishers
func (_mock *MockPublishers) DeletePublisher(context1 context.Context, uUID uuid.UUID) error {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePublisher")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPublishers_DeletePublisher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePublisher'
type MockPublishers_DeletePublisher_Call struct {
	*mock.Call
}

// DeletePublisher is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *MockPublishers_Expecter) DeletePublisher(context1 any, uUID any) *MockPublishers_DeletePublisher_Call {
	return &MockPublishers_DeletePublisher_Call{Call: _e.mock.On("DeletePublisher", context1, uUID)}
}

func (_c *MockPublishers_DeletePublisher_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *MockPublishers_DeletePublisher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPublishers_DeletePublisher_Call) Return(err error) *MockPublishers_DeletePublisher_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPublishers_DeletePublisher_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) error) *MockPublishers_DeletePublisher_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublisher provides a mock function for the type MockPublishers
func (_mock *MockPublishers) GetPublisher(context1 context.Context, uUID uuid.UUID) (entities.Publisher, error) {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for GetPublisher")
	}

	var r0 entities.Publisher
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entities.Publisher, error)); ok {
		return returnFunc(context1, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) entities.Publisher); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		r0 = ret.Get(0).(entities.Publisher)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(context1, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPublishers_GetPublisher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublisher'
type MockPublishers_GetPublisher_Call struct {
	*mock.Call
}

// GetPublisher is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *MockPublishers_Expecter) GetPublisher(context1 any, uUID any) *MockPublishers_GetPublisher_Call {
	return &MockPublishers_GetPublisher_Call{Call: _e.mock.On("GetPublisher", context1, uUID)}
}

func (_c *MockPublishers_GetPublisher_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *MockPublishers_GetPublisher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPublishers_GetPublisher_Call) Return(publisher entities.Publisher, err error) *MockPublishers_GetPublisher_Call {
	_c.Call.Return(publisher, err)
	return _c
}

func (_c *MockPublishers_GetPublisher_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) (entities.Publisher, error)) *MockPublishers_GetPublisher_Call {
	_c.Call.Return(run)
	return _c
}

// ListPublishers provides a mock function for the type MockPublishers
func (_mock *MockPublishers) ListPublishers(context1 context.Context) ([]entities.Publisher, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListPublishers")
	}

	var r0 []entities.Publisher
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entities.Publisher, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entities.Publisher); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Publisher)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPublishers_ListPublishers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublishers'
type MockPublishers_ListPublishers_Call struct {
	*mock.Call
}

// ListPublishers is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockPublishers_Expecter) ListPublishers(context1 any) *MockPublishers_ListPublishers_Call {
	return &MockPublishers_ListPublishers_Call{Call: _e.mock.On("ListPublishers", context1)}
}

func (_c *MockPublishers_ListPublishers_Call) Run(run func(context1 context.Context)) *MockPublishers_ListPublishers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPublishers_ListPublishers_Call) Return(publishers []entities.Publisher, err error) *MockPublishers_ListPublishers_Call {
	_c.Call.Return(publishers, err)
	return _c
}

func (_c *MockPublishers_ListPublishers_Call) RunAndReturn(run func(context1 context.Context) ([]entities.Publisher, error)) *MockPublishers_ListPublishers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePublisher provides a mock function for the type MockPublishers
func (_mock *MockPublishers) UpdatePublisher(context1 context.Context, publisher entities.Publisher) (entities.Publisher, error) {
	ret := _mock.Called(context1, publisher)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePublisher")
	}

	var r0 entities.Publisher
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Publisher) (entities.Publisher, error)); ok {
		return returnFunc(context1, publisher)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Publisher) entities.Publisher); ok {
		r0 = returnFunc(context1, publisher)
	} else {
		r0 = ret.Get(0).(entities.Publisher)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Publisher) error); ok {
		r1 = returnFunc(context1, publisher)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPublishers_UpdatePublisher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePublisher'
type MockPublishers_UpdatePublisher_Call struct {
	*mock.Call
}

// UpdatePublisher is a helper method to define mock.On call
//   - context1 context.Context
//   - publisher entities.Publisher
func (_e *MockPublishers_Expecter) UpdatePublisher(context1 any, publisher any) *MockPublishers_UpdatePublisher_Call {
	return &MockPublishers_UpdatePublisher_Call{Call: _e.mock.On("UpdatePublisher", context1, publisher)}
}

func (_c *MockPublishers_UpdatePublisher_Call) Run(run func(context1 context.Context, publisher entities.Publisher)) *MockPublishers_UpdatePublisher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Publisher
		if args[1] != nil {
			arg1 = args[1].(entities.Publisher)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPublishers_UpdatePublisher_Call) Return(publisher1 entities.Publisher, err error) *MockPublishers_UpdatePublisher_Call {
	_c.Call.Return(publisher1, err)
	return _c
}

func (_c *MockPublishers_UpdatePublisher_Call) RunAndReturn(run func(context1 context.Context, publisher entities.Publisher) (entities.Publisher, error)) *MockPublishers_UpdatePublisher_Call {
	_c.Call.Return(run)
	return _c
}
