// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateBook implements createBook operation.
	//
	// POST /books
	CreateBook(ctx context.Context, req *BookInput) (*Book, error)
	// CreatePublisher implements createPublisher operation.
	//
	// POST /publishers
	CreatePublisher(ctx context.Context, req *PublisherInput) (*Publisher, error)
	// DeleteBook implements deleteBook operation.
	//
	// DELETE /books/{id}
	DeleteBook(ctx context.Context, params DeleteBookParams) (*Deleted, error)
	// DeletePublisher implements deletePublisher operation.
	//
	// DELETE /publishers/{id}
	DeletePublisher(ctx context.Context, params DeletePublisherParams) (*Deleted, error)
	// GetBook implements getBook operation.
	//
	// GET /books/{id}
	GetBook(ctx context.Context, params GetBookParams) (*Book, error)
	// GetPublisher implements getPublisher operation.
	//
	// GET /publishers/{id}
	GetPublisher(ctx context.Context, params GetPublisherParams) (*Publisher, error)
	// ListBooks implements listBooks operation.
	//
	// GET /books
	ListBooks(ctx context.Context) ([]Book, error)
	// ListPublishers implements listPublishers operation.
	//
	// GET /publishers
	ListPublishers(ctx context.Context) ([]Publisher, error)
	// UpdateBook implements updateBook operation.
	//
	// PUT /books/{id}
	UpdateBook(ctx context.Context, req *BookInput, params UpdateBookParams) (*Book, error)
	// UpdatePublisher implements updatePublisher operation.
	//
	// PUT /publishers/{id}
	UpdatePublisher(ctx context.Context, req *PublisherInput, params UpdatePublisherParams) (*Publisher, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
