// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Merged schema.
// Ref: #/components/schemas/Book
type Book struct {
	Author          string    `json:"author"`
	Name            string    `json:"name"`
	Year            int       `json:"year"`
	Price           int64     `json:"price"`
	PublisherId     uuid.UUID `json:"publisherId"`
	PublicationYear int       `json:"publicationYear"`
	Quantity        int64     `json:"quantity"`
	ID              uuid.UUID `json:"id"`
}

// GetAuthor returns the value of Author.
func (s *Book) GetAuthor() string {
	return s.Author
}

// GetName returns the value of Name.
func (s *Book) GetName() string {
	return s.Name
}

// GetYear returns the value of Year.
func (s *Book) GetYear() int {
	return s.Year
}

// GetPrice returns the value of Price.
func (s *Book) GetPrice() int64 {
	return s.Price
}

// GetPublisherId returns the value of PublisherId.
func (s *Book) GetPublisherId() uuid.UUID {
	return s.PublisherId
}

// GetPublicationYear returns the value of PublicationYear.
func (s *Book) GetPublicationYear() int {
	return s.PublicationYear
}

// GetQuantity returns the value of Quantity.
func (s *Book) GetQuantity() int64 {
	return s.Quantity
}

// GetID returns the value of ID.
func (s *Book) GetID() uuid.UUID {
	return s.ID
}

// SetAuthor sets the value of Author.
func (s *Book) SetAuthor(val string) {
	s.Author = val
}

// SetName sets the value of Name.
func (s *Book) SetName(val string) {
	s.Name = val
}

// SetYear sets the value of Year.
func (s *Book) SetYear(val int) {
	s.Year = val
}

// SetPrice sets the value of Price.
func (s *Book) SetPrice(val int64) {
	s.Price = val
}

// SetPublisherId sets the value of PublisherId.
func (s *Book) SetPublisherId(val uuid.UUID) {
	s.PublisherId = val
}

// SetPublicationYear sets the value of PublicationYear.
func (s *Book) SetPublicationYear(val int) {
	s.PublicationYear = val
}

// SetQuantity sets the value of Quantity.
func (s *Book) SetQuantity(val int64) {
	s.Quantity = val
}

// SetID sets the value of ID.
func (s *Book) SetID(val uuid.UUID) {
	s.ID = val
}

// Ref: #/components/schemas/BookInput
type BookInput struct {
	Author          string    `json:"author"`
	Name            string    `json:"name"`
	Year            int       `json:"year"`
	Price           int64     `json:"price"`
	PublisherId     uuid.UUID `json:"publisherId"`
	PublicationYear int       `json:"publicationYear"`
	Quantity        int64     `json:"quantity"`
}

// GetAuthor returns the value of Author.
func (s *BookInput) GetAuthor() string {
	return s.Author
}

// GetName returns the value of Name.
func (s *BookInput) GetName() string {
	return s.Name
}

// GetYear returns the value of Year.
func (s *BookInput) GetYear() int {
	return s.Year
}

// GetPrice returns the value of Price.
func (s *BookInput) GetPrice() int64 {
	return s.Price
}

// GetPublisherId returns the value of PublisherId.
func (s *BookInput) GetPublisherId() uuid.UUID {
	return s.PublisherId
}

// GetPublicationYear returns the value of PublicationYear.
func (s *BookInput) GetPublicationYear() int {
	return s.PublicationYear
}

// GetQuantity returns the value of Quantity.
func (s *BookInput) GetQuantity() int64 {
	return s.Quantity
}

// SetAuthor sets the value of Author.
func (s *BookInput) SetAuthor(val string) {
	s.Author = val
}

// SetName sets the value of Name.
func (s *BookInput) SetName(val string) {
	s.Name = val
}

// SetYear sets the value of Year.
func (s *BookInput) SetYear(val int) {
	s.Year = val
}

// SetPrice sets the value of Price.
func (s *BookInput) SetPrice(val int64) {
	s.Price = val
}

// SetPublisherId sets the value of PublisherId.
func (s *BookInput) SetPublisherId(val uuid.UUID) {
	s.PublisherId = val
}

// SetPublicationYear sets the value of PublicationYear.
func (s *BookInput) SetPublicationYear(val int) {
	s.PublicationYear = val
}

// SetQuantity sets the value of Quantity.
func (s *BookInput) SetQuantity(val int64) {
	s.Quantity = val
}

// Ref: #/components/schemas/Deleted
type Deleted struct {
	Status string `json:"status"`
}

// GetStatus returns the value of Status.
func (s *Deleted) GetStatus() string {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *Deleted) SetStatus(val string) {
	s.Status = val
}

// ErrorStatusCode wraps Problem with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Problem
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Problem {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Problem) {
	s.Response = val
}

// Ref: #/components/schemas/Problem
type Problem struct {
	Error ProblemError `json:"error"`
}

// GetError returns the value of Error.
func (s *Problem) GetError() ProblemError {
	return s.Error
}

// SetError sets the value of Error.
func (s *Problem) SetError(val ProblemError) {
	s.Error = val
}

type ProblemError string

const (
	ProblemErrorInvalidInput                  ProblemError = "invalid_input"
	ProblemErrorConflict                      ProblemError = "conflict"
	ProblemErrorNotFound                      ProblemError = "not_found"
	ProblemErrorInternalError                 ProblemError = "internal_error"
	ProblemErrorBookAuthorRequired            ProblemError = "book_author_required"
	ProblemErrorBookNameRequired              ProblemError = "book_name_required"
	ProblemErrorBookYearInvalid               ProblemError = "book_year_invalid"
	ProblemErrorBookPriceNegative             ProblemError = "book_price_negative"
	ProblemErrorBookPublisherRequired         ProblemError = "book_publisher_required"
	ProblemErrorBookPublicationYearInvalid    ProblemError = "book_publication_year_invalid"
	ProblemErrorBookPublicationYearBeforeYear ProblemError = "book_publication_year_before_year"
	ProblemErrorBookQuantityNegative          ProblemError = "book_quantity_negative"
	ProblemErrorPublisherNameRequired         ProblemError = "publisher_name_required"
	ProblemErrorPublisherNameDuplicate        ProblemError = "publisher_name_duplicate"
	ProblemErrorBookDuplicate                 ProblemError = "book_duplicate"
	ProblemErrorBookPublisherNotFound         ProblemError = "book_publisher_not_found"
	ProblemErrorPublisherReferenced           ProblemError = "publisher_referenced"
	ProblemErrorInvalidRequest                ProblemError = "invalid_request"
	ProblemErrorInvalidJSON                   ProblemError = "invalid_json"
	ProblemErrorTrailingJSONData              ProblemError = "trailing_json_data"
	ProblemErrorInvalidID                     ProblemError = "invalid_id"
	ProblemErrorInvalidAuthor                 ProblemError = "invalid_author"
	ProblemErrorInvalidName                   ProblemError = "invalid_name"
	ProblemErrorInvalidYear                   ProblemError = "invalid_year"
	ProblemErrorInvalidPrice                  ProblemError = "invalid_price"
	ProblemErrorInvalidPublisherID            ProblemError = "invalid_publisher_id"
	ProblemErrorInvalidPublicationYear        ProblemError = "invalid_publication_year"
	ProblemErrorInvalidQuantity               ProblemError = "invalid_quantity"
)

// AllValues returns all ProblemError values.
func (ProblemError) AllValues() []ProblemError {
	return []ProblemError{
		ProblemErrorInvalidInput,
		ProblemErrorConflict,
		ProblemErrorNotFound,
		ProblemErrorInternalError,
		ProblemErrorBookAuthorRequired,
		ProblemErrorBookNameRequired,
		ProblemErrorBookYearInvalid,
		ProblemErrorBookPriceNegative,
		ProblemErrorBookPublisherRequired,
		ProblemErrorBookPublicationYearInvalid,
		ProblemErrorBookPublicationYearBeforeYear,
		ProblemErrorBookQuantityNegative,
		ProblemErrorPublisherNameRequired,
		ProblemErrorPublisherNameDuplicate,
		ProblemErrorBookDuplicate,
		ProblemErrorBookPublisherNotFound,
		ProblemErrorPublisherReferenced,
		ProblemErrorInvalidRequest,
		ProblemErrorInvalidJSON,
		ProblemErrorTrailingJSONData,
		ProblemErrorInvalidID,
		ProblemErrorInvalidAuthor,
		ProblemErrorInvalidName,
		ProblemErrorInvalidYear,
		ProblemErrorInvalidPrice,
		ProblemErrorInvalidPublisherID,
		ProblemErrorInvalidPublicationYear,
		ProblemErrorInvalidQuantity,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ProblemError) MarshalText() ([]byte, error) {
	switch s {
	case ProblemErrorInvalidInput:
		return []byte(s), nil
	case ProblemErrorConflict:
		return []byte(s), nil
	case ProblemErrorNotFound:
		return []byte(s), nil
	case ProblemErrorInternalError:
		return []byte(s), nil
	case ProblemErrorBookAuthorRequired:
		return []byte(s), nil
	case ProblemErrorBookNameRequired:
		return []byte(s), nil
	case ProblemErrorBookYearInvalid:
		return []byte(s), nil
	case ProblemErrorBookPriceNegative:
		return []byte(s), nil
	case ProblemErrorBookPublisherRequired:
		return []byte(s), nil
	case ProblemErrorBookPublicationYearInvalid:
		return []byte(s), nil
	case ProblemErrorBookPublicationYearBeforeYear:
		return []byte(s), nil
	case ProblemErrorBookQuantityNegative:
		return []byte(s), nil
	case ProblemErrorPublisherNameRequired:
		return []byte(s), nil
	case ProblemErrorPublisherNameDuplicate:
		return []byte(s), nil
	case ProblemErrorBookDuplicate:
		return []byte(s), nil
	case ProblemErrorBookPublisherNotFound:
		return []byte(s), nil
	case ProblemErrorPublisherReferenced:
		return []byte(s), nil
	case ProblemErrorInvalidRequest:
		return []byte(s), nil
	case ProblemErrorInvalidJSON:
		return []byte(s), nil
	case ProblemErrorTrailingJSONData:
		return []byte(s), nil
	case ProblemErrorInvalidID:
		return []byte(s), nil
	case ProblemErrorInvalidAuthor:
		return []byte(s), nil
	case ProblemErrorInvalidName:
		return []byte(s), nil
	case ProblemErrorInvalidYear:
		return []byte(s), nil
	case ProblemErrorInvalidPrice:
		return []byte(s), nil
	case ProblemErrorInvalidPublisherID:
		return []byte(s), nil
	case ProblemErrorInvalidPublicationYear:
		return []byte(s), nil
	case ProblemErrorInvalidQuantity:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ProblemError) UnmarshalText(data []byte) error {
	switch ProblemError(data) {
	case ProblemErrorInvalidInput:
		*s = ProblemErrorInvalidInput
		return nil
	case ProblemErrorConflict:
		*s = ProblemErrorConflict
		return nil
	case ProblemErrorNotFound:
		*s = ProblemErrorNotFound
		return nil
	case ProblemErrorInternalError:
		*s = ProblemErrorInternalError
		return nil
	case ProblemErrorBookAuthorRequired:
		*s = ProblemErrorBookAuthorRequired
		return nil
	case ProblemErrorBookNameRequired:
		*s = ProblemErrorBookNameRequired
		return nil
	case ProblemErrorBookYearInvalid:
		*s = ProblemErrorBookYearInvalid
		return nil
	case ProblemErrorBookPriceNegative:
		*s = ProblemErrorBookPriceNegative
		return nil
	case ProblemErrorBookPublisherRequired:
		*s = ProblemErrorBookPublisherRequired
		return nil
	case ProblemErrorBookPublicationYearInvalid:
		*s = ProblemErrorBookPublicationYearInvalid
		return nil
	case ProblemErrorBookPublicationYearBeforeYear:
		*s = ProblemErrorBookPublicationYearBeforeYear
		return nil
	case ProblemErrorBookQuantityNegative:
		*s = ProblemErrorBookQuantityNegative
		return nil
	case ProblemErrorPublisherNameRequired:
		*s = ProblemErrorPublisherNameRequired
		return nil
	case ProblemErrorPublisherNameDuplicate:
		*s = ProblemErrorPublisherNameDuplicate
		return nil
	case ProblemErrorBookDuplicate:
		*s = ProblemErrorBookDuplicate
		return nil
	case ProblemErrorBookPublisherNotFound:
		*s = ProblemErrorBookPublisherNotFound
		return nil
	case ProblemErrorPublisherReferenced:
		*s = ProblemErrorPublisherReferenced
		return nil
	case ProblemErrorInvalidRequest:
		*s = ProblemErrorInvalidRequest
		return nil
	case ProblemErrorInvalidJSON:
		*s = ProblemErrorInvalidJSON
		return nil
	case ProblemErrorTrailingJSONData:
		*s = ProblemErrorTrailingJSONData
		return nil
	case ProblemErrorInvalidID:
		*s = ProblemErrorInvalidID
		return nil
	case ProblemErrorInvalidAuthor:
		*s = ProblemErrorInvalidAuthor
		return nil
	case ProblemErrorInvalidName:
		*s = ProblemErrorInvalidName
		return nil
	case ProblemErrorInvalidYear:
		*s = ProblemErrorInvalidYear
		return nil
	case ProblemErrorInvalidPrice:
		*s = ProblemErrorInvalidPrice
		return nil
	case ProblemErrorInvalidPublisherID:
		*s = ProblemErrorInvalidPublisherID
		return nil
	case ProblemErrorInvalidPublicationYear:
		*s = ProblemErrorInvalidPublicationYear
		return nil
	case ProblemErrorInvalidQuantity:
		*s = ProblemErrorInvalidQuantity
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
// Ref: #/components/schemas/Publisher
type Publisher struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

// GetName returns the value of Name.
func (s *Publisher) GetName() string {
	return s.Name
}

// GetID returns the value of ID.
func (s *Publisher) GetID() uuid.UUID {
	return s.ID
}

// SetName sets the value of Name.
func (s *Publisher) SetName(val string) {
	s.Name = val
}

// SetID sets the value of ID.
func (s *Publisher) SetID(val uuid.UUID) {
	s.ID = val
}

// Ref: #/components/schemas/PublisherInput
type PublisherInput struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *PublisherInput) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *PublisherInput) SetName(val string) {
	s.Name = val
}
