// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateBookOperation      OperationName = "CreateBook"
	CreatePublisherOperation OperationName = "CreatePublisher"
	DeleteBookOperation      OperationName = "DeleteBook"
	DeletePublisherOperation OperationName = "DeletePublisher"
	GetBookOperation         OperationName = "GetBook"
	GetPublisherOperation    OperationName = "GetPublisher"
	ListBooksOperation       OperationName = "ListBooks"
	ListPublishersOperation  OperationName = "ListPublishers"
	UpdateBookOperation      OperationName = "UpdateBook"
	UpdatePublisherOperation OperationName = "UpdatePublisher"
)
