// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/validate"
)

func (s *ErrorStatusCode) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Response.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "Response",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *Problem) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Error.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "error",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ProblemError) Validate() error {
	switch s {
	case "invalid_input":
		return nil
	case "conflict":
		return nil
	case "not_found":
		return nil
	case "internal_error":
		return nil
	case "book_author_required":
		return nil
	case "book_name_required":
		return nil
	case "book_year_invalid":
		return nil
	case "book_price_negative":
		return nil
	case "book_publisher_required":
		return nil
	case "book_publication_year_invalid":
		return nil
	case "book_publication_year_before_year":
		return nil
	case "book_quantity_negative":
		return nil
	case "publisher_name_required":
		return nil
	case "publisher_name_duplicate":
		return nil
	case "book_duplicate":
		return nil
	case "book_publisher_not_found":
		return nil
	case "publisher_referenced":
		return nil
	case "invalid_request":
		return nil
	case "invalid_json":
		return nil
	case "trailing_json_data":
		return nil
	case "invalid_id":
		return nil
	case "invalid_author":
		return nil
	case "invalid_name":
		return nil
	case "invalid_year":
		return nil
	case "invalid_price":
		return nil
	case "invalid_publisher_id":
		return nil
	case "invalid_publication_year":
		return nil
	case "invalid_quantity":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
