// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"bookshop/backend/internal/domain/books/entities"
	"context"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBooks creates a new instance of MockBooks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBooks(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBooks {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockBooks{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockBooks is an autogenerated mock type for the Repository type
type MockBooks struct {
	mock.Mock
}

type MockBooks_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBooks) EXPECT() *MockBooks_Expecter {
	return &MockBooks_Expecter{mock: &_m.Mock}
}

// CreateBook provides a mock function for the type MockBooks
func (_mock *MockBooks) CreateBook(context1 context.Context, book entities.Book) (entities.Book, error) {
	ret := _mock.Called(context1, book)

	if len(ret) == 0 {
		panic("no return value specified for CreateBook")
	}

	var r0 entities.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Book) (entities.Book, error)); ok {
		return returnFunc(context1, book)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Book) entities.Book); ok {
		r0 = returnFunc(context1, book)
	} else {
		r0 = ret.Get(0).(entities.Book)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Book) error); ok {
		r1 = returnFunc(context1, book)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBooks_CreateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBook'
type MockBooks_CreateBook_Call struct {
	*mock.Call
}

// CreateBook is a helper method to define mock.On call
//   - context1 context.Context
//   - book entities.Book
func (_e *MockBooks_Expecter) CreateBook(context1 any, book any) *MockBooks_CreateBook_Call {
	return &MockBooks_CreateBook_Call{Call: _e.mock.On("CreateBook", context1, book)}
}

func (_c *MockBooks_CreateBook_Call) Run(run func(context1 context.Context, book entities.Book)) *MockBooks_CreateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Book
		if args[1] != nil {
			arg1 = args[1].(entities.Book)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBooks_CreateBook_Call) Return(book1 entities.Book, err error) *MockBooks_CreateBook_Call {
	_c.Call.Return(book1, err)
	return _c
}

func (_c *MockBooks_CreateBook_Call) RunAndReturn(run func(context1 context.Context, book entities.Book) (entities.Book, error)) *MockBooks_CreateBook_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBook provides a mock function for the type MockBooks
func (_mock *MockBooks) DeleteBook(context1 context.Context, uUID uuid.UUID) error {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBook")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBooks_DeleteBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBook'
type MockBooks_DeleteBook_Call struct {
	*mock.Call
}

// DeleteBook is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *MockBooks_Expecter) DeleteBook(context1 any, uUID any) *MockBooks_DeleteBook_Call {
	return &MockBooks_DeleteBook_Call{Call: _e.mock.On("DeleteBook", context1, uUID)}
}

func (_c *MockBooks_DeleteBook_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *MockBooks_DeleteBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBooks_DeleteBook_Call) Return(err error) *MockBooks_DeleteBook_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBooks_DeleteBook_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) error) *MockBooks_DeleteBook_Call {
	_c.Call.Return(run)
	return _c
}

// GetBook provides a mock function for the type MockBooks
func (_mock *MockBooks) GetBook(context1 context.Context, uUID uuid.UUID) (entities.Book, error) {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for GetBook")
	}

	var r0 entities.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (entities.Book, error)); ok {
		return returnFunc(context1, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) entities.Book); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		r0 = ret.Get(0).(entities.Book)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(context1, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBooks_GetBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBook'
type MockBooks_GetBook_Call struct {
	*mock.Call
}

// GetBook is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *MockBooks_Expecter) GetBook(context1 any, uUID any) *MockBooks_GetBook_Call {
	return &MockBooks_GetBook_Call{Call: _e.mock.On("GetBook", context1, uUID)}
}

func (_c *MockBooks_GetBook_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *MockBooks_GetBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBooks_GetBook_Call) Return(book entities.Book, err error) *MockBooks_GetBook_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockBooks_GetBook_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) (entities.Book, error)) *MockBooks_GetBook_Call {
	_c.Call.Return(run)
	return _c
}

// ListBooks provides a mock function for the type MockBooks
func (_mock *MockBooks) ListBooks(context1 context.Context) ([]entities.Book, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListBooks")
	}

	var r0 []entities.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entities.Book, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entities.Book); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBooks_ListBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBooks'
type MockBooks_ListBooks_Call struct {
	*mock.Call
}

// ListBooks is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockBooks_Expecter) ListBooks(context1 any) *MockBooks_ListBooks_Call {
	return &MockBooks_ListBooks_Call{Call: _e.mock.On("ListBooks", context1)}
}

func (_c *MockBooks_ListBooks_Call) Run(run func(context1 context.Context)) *MockBooks_ListBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBooks_ListBooks_Call) Return(books []entities.Book, err error) *MockBooks_ListBooks_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockBooks_ListBooks_Call) RunAndReturn(run func(context1 context.Context) ([]entities.Book, error)) *MockBooks_ListBooks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBook provides a mock function for the type MockBooks
func (_mock *MockBooks) UpdateBook(context1 context.Context, book entities.Book) (entities.Book, error) {
	ret := _mock.Called(context1, book)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBook")
	}

	var r0 entities.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Book) (entities.Book, error)); ok {
		return returnFunc(context1, book)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Book) entities.Book); ok {
		r0 = returnFunc(context1, book)
	} else {
		r0 = ret.Get(0).(entities.Book)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Book) error); ok {
		r1 = returnFunc(context1, book)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBooks_UpdateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBook'
type MockBooks_UpdateBook_Call struct {
	*mock.Call
}

// UpdateBook is a helper method to define mock.On call
//   - context1 context.Context
//   - book entities.Book
func (_e *MockBooks_Expecter) UpdateBook(context1 any, book any) *MockBooks_UpdateBook_Call {
	return &MockBooks_UpdateBook_Call{Call: _e.mock.On("UpdateBook", context1, book)}
}

func (_c *MockBooks_UpdateBook_Call) Run(run func(context1 context.Context, book entities.Book)) *MockBooks_UpdateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Book
		if args[1] != nil {
			arg1 = args[1].(entities.Book)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBooks_UpdateBook_Call) Return(book1 entities.Book, err error) *MockBooks_UpdateBook_Call {
	_c.Call.Return(book1, err)
	return _c
}

func (_c *MockBooks_UpdateBook_Call) RunAndReturn(run func(context1 context.Context, book entities.Book) (entities.Book, error)) *MockBooks_UpdateBook_Call {
	_c.Call.Return(run)
	return _c
}
