FROM golang:1.25-alpine AS build
RUN go install -tags 'no_clickhouse no_mssql no_mysql no_sqlite3 no_ydb' github.com/pressly/goose/v3/cmd/goose@v3.25.0

FROM alpine:3.21
COPY --from=build /go/bin/goose /usr/local/bin/goose
COPY migrations /migrations
ENTRYPOINT ["sh", "-c", "exec goose \"$@\" 2>&1", "--"]
